"""empty message

Revision ID: 0ec89760ec82
Revises: 27da4530a3db
Create Date: 2019-07-16 14:27:14.661785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec89760ec82'
down_revision = '27da4530a3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'customer', ['zipcode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('customer', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('customer', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
