"""empty message

Revision ID: 1eb4bc07045e
Revises: 5f7c259b90f5
Create Date: 2019-07-16 14:39:21.981051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb4bc07045e'
down_revision = '5f7c259b90f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
