"""empty message

Revision ID: 234ba56b430e
Revises: 1eb4bc07045e
Create Date: 2019-07-16 14:56:19.084794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234ba56b430e'
down_revision = '1eb4bc07045e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('customer', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'lng')
    op.drop_column('customer', 'lat')
    # ### end Alembic commands ###
