"""empty message

Revision ID: 27da4530a3db
Revises: 69a66c4bce2d
Create Date: 2019-07-16 14:21:24.882055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27da4530a3db'
down_revision = '69a66c4bce2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'count')
    # ### end Alembic commands ###
