"""empty message

Revision ID: 844b2f608eb0
Revises: eae3ccf3a706
Create Date: 2019-07-16 13:47:00.012256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844b2f608eb0'
down_revision = 'eae3ccf3a706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('zip', sa.Integer(), nullable=True))
    op.drop_column('customer', 'city')
    op.drop_column('customer', 'name')
    op.drop_column('customer', 'state')
    op.drop_column('customer', 'address1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('address1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('city', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('customer', 'zip')
    # ### end Alembic commands ###
