"""empty message

Revision ID: eae3ccf3a706
Revises: 05ccb862813d
Create Date: 2019-07-15 13:42:19.170127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae3ccf3a706'
down_revision = '05ccb862813d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('customer', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'state')
    op.drop_column('customer', 'city')
    # ### end Alembic commands ###
